voldikss/vim-floaterm

autoload/floaterm.vim

I was setting width and height of `vim-floatterm` like this and found that it doesn't work.
```vim
let g:floaterm_height = &lines * 0.8
```
```vim
Error detected while processing function floaterm#toggleTerminal[30]..<SNR>128_openTerminalFloating:
E5555: API call: 'height' key must be a positive Integer
```
This PR fixes the issue by calling `float2nr` for arguments `a:width` and `a:height` to remove the part after decimal points from these arguments.

Fix issue where g:floaterm_width and g:floaterm_height are unable to set with decimal numbers

---

README.md
autoload/floaterm.vim

If these variables are given as float numbers (between 0 and 1),
they could denote the width/height relative to the vim window.
An example usage:
```
let g:floaterm_width = 0.9    " Use 90% of the width for floaterm
```

Allow float values for g:floaterm_{width,height}

---

README.md

用词错误，opacity的意思是“不透明度”

---

rplugin/python3/denite/kind/floaterm.py

I found the current build shows the top of the buffer lines in the preview window, so the shown lines will not change even after it scrolls many lines.
This commit solves this with showing the last non-empty lines of buffers.
<dl>
<dt>before</dt>
<dd><img width="745" alt="スクリーンショット 0002-02-06 21 11 09" src="https://user-images.githubusercontent.com/1239245/73937991-ad684500-4929-11ea-8bd6-b07d7804450a.png"></dd>
<dt>after</dt>
<dd><img width="744" alt="スクリーンショット 0002-02-06 21 11 59" src="https://user-images.githubusercontent.com/1239245/73937999-b48f5300-4929-11ea-9843-a8d8d11435a7.png"></dd>
</dl>

Show the last output in the preview window

---

bin/floaterm

It raises an error by executing `floaterm foo` in fish.
```
~ ❯❯❯ floaterm nvim.log
Failed to execute process '/path/to/vim-floaterm/bin/floaterm'. Reason:
exec: Exec format error
The file '/path/to/vim-floaterm/bin/floaterm' is marked as an executable but could not be run by the operating system.
```
This patch fixes the shebang and removes unnecessary modeline. Vim can detects as the `sh` filetype without the modeline.

Fix shebang to detect to be an executable in fish

---

autoload/floaterm/wrapper/fff.vim

By default, `fff` [will open at the directory of the file being edited](https://github.com/dylanaraps/fff/blob/d7f5092277165b3dbcc83c358b6da123f274c947/fff#L1077), this works fine most of the time. However, if you want to edit a file outside of your project directory (like a dotfile) then `:Floaterm fff` will not show files from your project.
Ran into this issue because my vim config opens a "vim tip of the day" file when opened, and this was causing `fff` to show the wrong directory.

fix: Always open fff in current working directory

---

autoload/floaterm/wrapper/fff.vim

Sorry about the drip-feed of PRs, I keep discovering issues.
This fixes an issue whereby pressing `q` in `fff` would delete
the current buffer resulting in an empty screen.
Upon exiting `fff`, if no file was opened (by pressing `l` or `enter`)
then the vimmer should be returned to the existing buffer.

fix: Only delete buffer if new file opened

---

autoload/floaterm/wrapper/ranger.vim

Ranger was opening a cached directory path, meaning that when you invoke `:FloatermNew ranger` it would open at the path of the last project you used it in.

Always open the current directory in ranger

---

autoload/floaterm/wrapper/fff.vim
autoload/floaterm/wrapper/ranger.vim

What this does is open ranger at the path of the current file / directory from vim's perspective. It also respects the vim-user's working directory setting (`s:original_dir`), which can be set by the .vimrc, e.g.
`autocmd VimEnter * silent! lcd %:p:h " Set working directory to current file / dir from perspective of vim`
`autocmd VimEnter * silent! lcd $PWD " Set working directory to current file / dir from perspective of shell`

Open ranger at the path of the current file, maintain working directory

---

autoload/floaterm/wrapper/lf.vim

Realised this code wasn't actually working. 
The directory of the current file is cached in vim using `lcd %:p:h`, but without `getcwd()`, `lf` just opens at `$PWD`.

fix: Fix current directory issue in lf.vim

---

README.md
autoload/floaterm/wrapper/vifm.vim

Another terminal file manager wrapper...My personal favourite file manager has been [vifm](https://github.com/vifm/vifm). It does have a vim plugin but doesn't provide a way to open in floating windows, maybe I missed something in their doc. Looking at the wrapper example, I figured making a floaterm wrapper is a much easier job.
I've read through the doc of the added new wrapper and made some small adjustment based on the ranger wrapper. The reason I've used the `expand("%:p:h")` instead of `getcwd()` is that I'm trying to manipulate the same behaviour of their vim plugin (Open the manager and set the path to current file path instead of root path).
If you are interested in having a look at vifm, here is a great intro video [vifm - The Terminal File Manager For The Vim-Centric …

Added Vifm wrapper

---

autoload/clap/provider/floaterm.vim
autoload/floaterm.vim
autoload/floaterm/terminal.vim
plugin/floaterm.vim

New API for selecting size for each floaterm. Old API remains the same and is unbroken.
I wasn't too sure of making these changes, as I'm new to this viml business. Comments are welcome. :)
Example: 
```
call floaterm#new('', {'height':0.5, 'width':0.9})
```

add api for selecting size

---

autoload/floaterm.vim
autoload/floaterm/cmdline.vim
autoload/floaterm/terminal.vim
plugin/floaterm.vim

```
FloatermNew name='test1'
FloatermToggle test1
FloatermSend test1
```
Backwards compatibility is maintained.
Closes #69

add ability to name floaterm terminals

---

autoload/floaterm/wrapper/vifm.vim

Currently, bare file paths are passed to vifm from the vifm.vim wrapper, which can cause errors when a file path contains spaces.
This surrounds all paths passed to vifm with quotes in order to prevent this. It would probably be wise to mimic this behaviour across all wrappers, however since I haven't tested this with any of the other external programs this package provides wrappers for I thought it best to leave it at vifm.vim.

Added quotes around file paths passed to vifm from wrapper

---

autoload/floaterm/wrapper/fff.vim
autoload/floaterm/wrapper/lf.vim
autoload/floaterm/wrapper/nnn.vim
autoload/floaterm/wrapper/ranger.vim

Following on from #107 I added quotes to the file paths in all other other wrappers. Not tested these but I don't see how it would cause an issue and should fix any potential issues with passing paths containing spaces.

Added quotes around file paths passed to all external file managers from wrappers

---

rplugin/python3/denite/source/floaterm.py

Now `floaterm#hide()` needs arguments.

Fix for the new interface

---

README.md
autoload/floaterm/cmdline.vim

This implementation behaves as follows:
- Any option like `--opt` is not parsed by floaterm, it is given to the `cmd`
- Any option like `--opt=` throws a warning and doesn't set any value for `b:floaterm_opts[opt]`
Note that in the second case the floaterm is still opened successfully, but without setting the value of `opt`. Let me know what you think, maybe you prefer to error and abort completely?

Fix cmdline option parser #176

---

autoload/floaterm.vim
test/test_commands/test_FloatermToggle.vader

Currently, the `floaterm#terminal#toggle` method doesn't work when a named argument is passed (It will always create a new buffer, even if one has already been created). On inspection, this seems to be an issue with the order of arguments passed to `floaterm#new` - the `jobopts` and `opts` arguments seem to be switched. Reversing them fixes the issue.

Fix floaterm#toggle with a name parameter

---

autoload/floaterm/window.vim

The `hide` function accepts `winnr` instead of `bufnr`.
Therefore, I implemented the logic to convert from `bufnr` to `winnr`.
modified:   autoload/floaterm/window.vim

Fix `floaterm#window#hide_floaterm` when `g:floaterm_wintype = 'normal'`

---

README.md

My change
```diff
- :FloatermNew --autoclose=0 gcc % -o %< && ./%<`
+ :FloatermNew --autoclose=0 gcc % -o %< && ./%<
```
While reading the documentation I found an extra backtick/backquote in the example codeblock for compiling and running  
C code, which was causing this error in zsh:
Command works as expected after removing the extra backtick.

Fix Codeblock in README

---

rplugin/python3/deoplete/source/floaterm.py

As agreed.
I fixed small typo in the Python function for Deoplete.
`floaterm#util#getbufline` -> `floaterm#util#getbuflines`
BR,
Alexey

typo in the function name. correct is floaterm#util#getbuflines

---

autoload/floaterm/terminal.vim

Avoids error 'Using a Job as a Number'

Correctly check if job exists with job_status

---

README.md
autoload/floaterm.vim
autoload/floaterm/edita/neovim/client.vim
autoload/floaterm/edita/neovim/editor.vim
autoload/floaterm/edita/neovim/util.vim
autoload/floaterm/edita/setup.vim
autoload/floaterm/edita/vim/client.vim
autoload/floaterm/edita/vim/editor.vim
autoload/floaterm/terminal.vim
autoload/floaterm/util.vim
bin/floaterm
bin/floaterm.cmd
doc/floaterm.txt
plugin/floaterm.vim
test/test_options/test-gitcommit.vader

* No external dependencies
* Also works for vim8
- get rid of `'floaterm`' value of `g:floaterm_gitcommit'`. Fallback: `'vsplit'`.

Rework pseudo $EDITOR in floaterm

---

README.md
autoload/floaterm.vim
autoload/floaterm/terminal.vim
autoload/floaterm/wrapper/fff.vim
autoload/floaterm/wrapper/fzf.vim
autoload/floaterm/wrapper/lf.vim
autoload/floaterm/wrapper/nnn.vim
autoload/floaterm/wrapper/ranger.vim
autoload/floaterm/wrapper/rg.vim
autoload/floaterm/wrapper/vifm.vim

- function arguments change
```vim
floaterm#wrapper#xxx#(cmd)
```
was changed to
```vim
floaterm#wrapper#xxx#(cmd, jobopts, config)
```
- return value
```vim
return [cmd, {'on_exit': funcref('s:xxx_callback')}, v:false]
```
was changed to
```vim
return [v:false, cmd]
```
and there is one more line
```vim
let a:jobopts.on_exit = funcref('s:xxx_callback')
```

Wrapper api

---

README.md
doc/floaterm.txt

FloatermSend may be marked with a "!" in some cases.

Fix FloatermSend command in the documentation

---

README.md
autoload/floaterm/cmdline.vim

Based on [this](https://www.reddit.com/r/neovim/comments/kh33rc/is_it_possible_to_open_floaterm_in_cwd_of_current/) post, I'm not the only one interested in this functionality.
This PR proposes a minimalistic way to solve this. Let me know what you think. If you like the idea, I can also update the docs.

Add option to start floaterm in dir of active buffer

---

autoload/floaterm/wrapper/rg.vim

While all other shells work nicely with both single and double-quotes, cmd on Windows only likes double quotes. 
This is a simple fix that will likely not affect other shells.

Use double quotes for ripgrep

---

bin/floaterm.cmd

The floaterm command was always failing on Neovim because VIM_EXE is never defined on Neovim.
So the check for VIM_EXE variable should be put inside the `:vim` function.
The command `floaterm filename.txt` works on Neovim now.

Fix floaterm.cmd

---

autoload/floaterm/wrapper/rg.vim

Reduce noise by preventing `ripgrep` to matching everything
Since `ripgrep` gets an empty pattern it matches every file which is then passed to FZF.
I'm not sure was it on purpose but because of this, there is a lot of noise for further `fzf` filtering.
Remove empty args from ripgrep call. 
Manually

remove empty pattern

---

autoload/floaterm/wrapper/rg.vim

Add `bat` line highlight to `fzf` --preview
It wasn't easy to see which line the result was found on.
using bat `--highlight-line` art
I manually tested that the highlight happens.

add highlight to bat

---

README.md

Hi 👋 
I noticed an inconsistency in the README.md where the `FloatermNC` configuration example didn't match the demo shown. 
Hope this small fix is okay!

docs: Change 'guibg' to 'guifg' in FloatermNC Example

---

autoload/floaterm.vim

Use name instead of termname like other cmd

fix: use name instead of termname like other cmd

---

autoload/floaterm/wrapper/vifm.vim

This fixes opening files like `foo#bar` in vifm

fnameescape for vifm callback

---

README.md
autoload/floaterm/util.vim
plugin/floaterm.vim

With setting g:floaterm_giteditor = 0 (which defaults to 1),
floaterm's git editor integration is disabled and `$GIT_EDITOR`
won't be overriden.

feat: Add an option to disable floaterm's GIT_EDITOR override

---

autoload/floaterm/wrapper/broot.vim

There is no more `--out` command in `broot`.
The new `--outcmd` option does not write to file when `:print_filename` is called.
Fix it by redirecting `broot` output to the tmp file used in `--out` option.

fix(broot): use redirect to file instead of --out

---

autoload/floaterm/util.vim
autoload/floaterm/wrapper/broot.vim

Pass on line number as broot allow to search for text in files (e.g. `c/printf`) and provides line number of the selected match. Along the way fix `floaterm#util#open` as it was ignoring `lnum` and `text` of the first entry in `locations`.

feat(broot): use line number from broot search

---

README.md

When you will try to call `:FloatermNew rg` without pre-installed `fzf` the window will blink without any output

docs(readme): add requirements section to ripgrep

---

README.md

- add link to https://github.com/jremmen/vim-ripgrep because it not works without the plugin
- add info about example of keymap to trigger a Rg with ripgrep and floaterm

docs(readme): add link to vim ripgrep and hotkey

---

autoload/floaterm/path.vim

E492: Not an editor command: tcd /home/jerry
#401

E492: Not an editor command: tcd /home/jerry

---

README.md
autoload/floaterm/buffer.vim
autoload/floaterm/cmdline.vim
autoload/floaterm/config.vim
autoload/floaterm/window.vim
doc/floaterm.txt
plugin/floaterm.vim
test/test_functions/test-floaterm_cmdline.vader
test/test_options/test-title-position.vader

Hello,
I would like to add `--titleposition` option to set the position of the floaterm title.
This change add `left` (default), `center` and `right` position, it should be feasible to also add `top` and `bottom` options.
Example:
| left | center | right |
|:----:|:--------:|:------:|
| ![left](https://github.com/voldikss/vim-floaterm/assets/6067072/c11a7c21-acb1-4d65-923d-9b7bceb764b4) | ![center](https://github.com/voldikss/vim-floaterm/assets/6067072/ae29ca9f-1068-41fa-9c93-8b23b04614e8) | ![right](https://github.com/voldikss/vim-floaterm/assets/6067072/77336ecd-ac27-4ade-ac35-2ebc86220382) |

feat: add title position option

---

autoload/floaterm/buffer.vim
autoload/floaterm/window.vim
test/test_options/test-title-position.vader

Hello,
I noticed with CI that my previous feature (#410 ) only worked with neovim. 
So I added some modification and refactoring to enable it for vim popup.
This do not introduce any behavior change with default `--titleposition=left` when calling `popup_getoptions(win_getid()).title`. 
Nonetheless for `center` and `right` the vim popup title include borderchars and might be inconsistent with title when using `left` alignment.
I'm not familiar with vim popup, so a better solution may exist.
Let me know what you think and feel free to edit the PR.
Note: CI pass in https://github.com/lucobellic/vim-floaterm/actions/runs/4968353492

fix: set --titleposition functional for vim popup

---

autoload/floaterm/path.vim

```
haslocaldir([{winnr} [, {tabnr}]])			*haslocaldir()*
The result is a Number:
1   when the window has set a local directory via |:lcd|
2   when the tab-page has set a local directory via |:tcd|
0   otherwise.
Without arguments use the current window.
With {winnr} use this window in the current tab page.
With {winnr} and {tabnr} use the window in the specified tab
page.
{winnr} can be the window number or the |window-ID|.
If {winnr} is -1 it is ignored and only the tabpage is used.
Return 0 if the arguments are invalid.
Examples: >
if haslocaldir() == 1
" window local directory case
elseif haslocaldir() == 2
" tab-local directory case
else
" global directory case
endif
" current window
:echo haslocaldir()
:echo haslocaldir(0)
:echo haslocaldir(0, 0)
" window n in current tab page
:echo …
```

Use haslocaldir() to choose which flavor of cd to use

---

autoload/floaterm/path.vim

Error after FloatermNew command in window. Error seem because there is no space after cd. Neovim message showed: 
`Error detected while processing function floaterm#run[7]..floaterm#new[36]..floaterm#terminal#open[22]..floaterm#path#chdir:
line    2:
E492: Not an editor command: cdC:\Users\xxx`
This fix has not tested against linux, but I think this error not too complex.

fix:space after cd

---

autoload/floaterm/edita/neovim/editor.vim
autoload/floaterm/edita/vim/editor.vim

[`git-revise`](https://github.com/mystor/git-revise) is an external Git tool mimicking `git-rebase`. It operates in-memory and also offers a `cut` command for splitting commits. It has an interactive mode just like `git-rebase`.
Currently, attempting `git revise --interactive` from floaterm fails, because `$EDITOR` is called with the TODO file and exits immediately.
This PR adds `git-revise-todo` to the search list in `floaterm#edita#{neo,}vim#editor#open`.

fix: Support `git revise --interactive`

---

README.md
autoload/floaterm/cmdline.vim
autoload/floaterm/path.vim

This PR adds a literal for the `--cwd` option, namely `<buffer-root>`, which represents the project root directory of the active buffer. This fits my use case, and possibly others I hope, like when editing config files for my vim/neovim placed in a dedicated repository while I'm working on a regular project.

feat: add `--cwd=<buffer-root>` option

---

autoload/floaterm/edita/vim/client.vim

fixes https://github.com/voldikss/vim-floaterm/issues/349 where gvim was opened in terminal vim

use exepath of progname in case progpath erroneous

---

autoload/floaterm/path.vim

sort of fix for issue #423 
`haslocaldir()` function works differently on neovim
```vim
haslocaldir([{winnr} [, {tabnr}]])                               *haslocaldir()*
The result is a Number, which is 1 when the window has set a
local path via |:lcd| or when {winnr} is -1 and the tabpage
has set a local path via |:tcd|, otherwise 0.
```
but to be real I do not understand why floaterm need to call `:cd` or `:tcd` command.
what is the purpose of changing editor(other windows) cwd when opening terminal? 🤔
wouldn’t it be enough just to use `:lcd` for floaterm window? 🤔

fix chdir function for nvim

---

autoload/floaterm/window.vim

Hi @voldikss, thanks for creating so awesome plugin. it makes me work on the terminal so happy.
Neovim 0.11 had introduced a new global option named [winborder](https://github.com/neovim/neovim/pull/31074). And vim-floaterm had drawn the border by creating an extra border window now, it's duplicated if I set winborder as rounded
this pr fixes it by cancel creating an extra border window.
the window screenshot is below if the user hasn't set [winborder]
the window screenshot is below if the user has set [winborder]

fix: respect winborder option which introduced since neovim 0.11

---

autoload/floaterm/window.vim

If deleting a file, either from within floaterm itself or while floaterm is open, the `silent` will silence the 'E211 File "{filename}" no longer available' error if floaterm is hidden before another call to `:checktime` is made. A common situation when this can happen is when using floaterm to check out a branch that doesn't contain all the files currently being edited.
Given that it's not possible to just add another :checktime to re-trigger the E211 error (since the original :checktime has updated the timestamps), it seems appropriate to expect those who don't want the possible (n)vim output resulting from a :checktime to explicitly silence suppress it to avoid forcing those who do want the output to resort to custom workarounds.
I noticed …

Un-silence checktime of floaterm#window#hide

---

autoload/floaterm/path.vim

Fix for #453.
Older Vim versions (e.g., 8.0.1763) do not support default values in function definitions.
Replace the default argument with vararg to maintain compatibility.

fix: support Vim 8.0 without default argument values
