voldikss/vim-floaterm

- README.md
- autoload/floaterm.vim
- plugin/floaterm.vim
Hi, what is your opinion on adding someting that will let users set window positions like `topright`, `bottomleft` etc..
> Add floaterm_position

- README.md
(first, let me say that I love what you have shared! Thank you!)
Also, huge +1 for having docs and a plugin that "just works". Great plugin!
> docs: Adding 'center' to list of positions

- README.md
- autoload/floaterm/wrapper/fff.vim
> Add fff wrapper

- autoload/floaterm/wrapper/lf.vim
This PR adds a wrapper for [gokcehan/lf](https://github.com/gokcehan/lf)
> Add wrapper for lf (github.com/gokcehan/lf)

- autoload/floaterm/wrapper/ranger.vim
Now the currently open file will be selected in ranger.
> select the proper file when opening ranger

- autoload/floaterm.vim
- autoload/floaterm/floatwin.vim
- autoload/floaterm/terminal.vim
Toggling is now independent.
Closes #74
> make toggling independent

- autoload/floaterm/cmdline.vim
- autoload/floaterm/floatwin.vim
- autoload/floaterm/terminal.vim
- plugin/floaterm.vim
```
FloatermUpdate wintype='normal' height=0.4
```
Closes #57
> add ability to update window opts

- README.md
- autoload/floaterm.vim
- autoload/floaterm/buffer.vim
- autoload/floaterm/buflist.vim
- autoload/floaterm/cmdline.vim
- autoload/floaterm/terminal.vim
- autoload/floaterm/util.vim
- autoload/floaterm/window.vim
- plugin/floaterm.vim
> Add vim8 popup support

- README.md
- autoload/floaterm.vim
- autoload/floaterm/cmdline.vim
- plugin/floaterm.vim
> Command `:FloatermSend` accepts `cmd` argument

- autoload/floaterm.vim
Looking at the README it seemed that I would be allowed to create my own wrapper. With this small tweak, it seems to work fine.
> Allow user-defined wrappers

- autoload/floaterm/terminal.vim
`s:popup` should be `s:has_popup`.
> fix undefined variable

- README.md
- autoload/floaterm.vim
- autoload/floaterm/buflist.vim
- plugin/floaterm.vim
> FloatermFirst and FloatermLast

- autoload/floaterm/terminal.vim
Looks like something went wrong on your last change 😸 
By the way thank you for maintaining this great plugin 👍
> Correctly check if job is null

- README.md
> Add reference to lf.vim

- README.md
- autoload/floaterm/wrapper/xplr.vim
Add support for picking files using [xplr](https://github.com/sayanarijit/xplr).
> Add xplr wrapper

- autoload/floaterm/wrapper/broot.vim
> Reverse config order in broot wrapper

- autoload/floaterm/wrapper/vifm.vim
> Handle directories in Vifm wrapper

- autoload/floaterm/terminal.vim
> fix(wrapper): Fix messy ui for ranger & nnn wrapper

- plugin/floaterm.vim
Closes #332
Draft until tested.
> fix: Throw error on vim if compiled without 'terminal'

- doc/floaterm.txt
Hi,
This is just a link fix for the command line tools we discussed in #358.
Thanks
> Fixing link for the command line tools

- README.md
- autoload/floaterm/wrapper/joshuto.vim
https://github.com/kamiyaa/joshuto
> Support file manager joshuto

- README.md
- autoload/floaterm/wrapper/yazi.vim
I'm not sure how many file manager integrations you're looking to have, but here's another one!
> feat: add yazi support

- autoload/floaterm/edita/neovim/editor.vim
- autoload/floaterm/edita/vim/editor.vim
This fixes the error:
E211: File "<some_path>/.git/MERGE_MSG" no longer available
> Add MERGE_MSG to floaterm#edita#neovim#editor#open
